# Generated by Django 5.1.6 on 2025-02-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='webpage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
